/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShortenedUrlRouteImport } from './routes/$shortenedUrl'
import { Route as IndexRouteImport } from './routes/index'

const ShortenedUrlRoute = ShortenedUrlRouteImport.update({
  id: '/$shortenedUrl',
  path: '/$shortenedUrl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$shortenedUrl': typeof ShortenedUrlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$shortenedUrl': typeof ShortenedUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$shortenedUrl': typeof ShortenedUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$shortenedUrl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$shortenedUrl'
  id: '__root__' | '/' | '/$shortenedUrl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShortenedUrlRoute: typeof ShortenedUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$shortenedUrl': {
      id: '/$shortenedUrl'
      path: '/$shortenedUrl'
      fullPath: '/$shortenedUrl'
      preLoaderRoute: typeof ShortenedUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShortenedUrlRoute: ShortenedUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
